### ISSUE TITLE
Add Web runner back when Flutter stable increments.

### ISSUE THREAD

**Issue by domesticmouse** [Dev-Owl/flutter_space#2]
Feel free to assign this task to me =)

**Comment by Dev-Owl** [comment]
Right now, Flutters documentation points out that beta has a working fragment shader support for web. So I guess it will soon be in stable 😊
Thanks for taking care 👍

**Comment by domesticmouse** [comment]
> Right now, Flutters documentation points out that beta has a working fragment shader support for web. So I guess it will soon be in stable 😊
> 
> Thanks for taking care 👍

I've not yet verified your code against Flutter beta on the web, but yeah it should work. I'll find out soon 😏

**Comment by domesticmouse** [comment]
Please land #3
